### ISSUE TITLE
Add CI pipeline using GitHub Actions

### ISSUE THREAD

**Issue by neelkamath** [neelkamath/brians-brain#1]
Create a GitHub Actions workflow for tests to run on every push and pull request to this repo. Here's a [hint](https://github.com/neelkamath/highlife/blob/master/.github/workflows/workflow.yml) of what it should look like. Remember to make sure the test artifacts are uploaded even if the tests don't pass: that's when we want to see those reports!

**Comment by AshrayShetty4** [comment]
I would like to work on this issue!
